// https://my.truffleteams.com/#/r/7cb0105a-c4dc-4523-9278-916ba53a394d/d

export const abi = [
  {
    type: 'constructor',
    inputs: [{ name: 'dai', type: 'address', internalType: 'address' }],
    stateMutability: 'nonpayable',
  },
  {
    name: 'ActivateMoneyPool',
    type: 'event',
    inputs: [
      {
        name: 'id',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'owner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'sustainabilityTarget',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'duration',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'want',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    name: 'CollectRedistributions',
    type: 'event',
    inputs: [
      {
        name: 'sustainer',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'amount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    name: 'CollectSustainements',
    type: 'event',
    inputs: [
      {
        name: 'owner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'amount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    name: 'ConfigureMoneyPool',
    type: 'event',
    inputs: [
      {
        name: 'id',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'owner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'sustainabilityTarget',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'duration',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'want',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    name: 'InitializeMoneyPool',
    type: 'event',
    inputs: [
      {
        name: 'id',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'owner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    name: 'SustainMoneyPool',
    type: 'event',
    inputs: [
      {
        name: 'id',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'owner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'sustainer',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'amount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    name: 'DAI',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    constant: true,
    stateMutability: 'view',
  },
  {
    name: 'latestMoneyPoolIds',
    type: 'function',
    inputs: [{ name: '', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    constant: true,
    stateMutability: 'view',
  },
  {
    name: 'moneyPoolCount',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    constant: true,
    stateMutability: 'view',
  },
  {
    name: 'moneyPools',
    type: 'function',
    inputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      { name: 'owner', type: 'address', internalType: 'address' },
      { name: 'want', type: 'address', internalType: 'address' },
      {
        name: 'sustainabilityTarget',
        type: 'uint256',
        internalType: 'uint256',
      },
      {
        name: 'currentSustainment',
        type: 'uint256',
        internalType: 'uint256',
      },
      { name: 'start', type: 'uint256', internalType: 'uint256' },
      { name: 'duration', type: 'uint256', internalType: 'uint256' },
      { name: 'exists', type: 'bool', internalType: 'bool' },
      {
        name: 'previousMoneyPoolId',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    constant: true,
    stateMutability: 'view',
  },
  {
    name: 'redistributionPool',
    type: 'function',
    inputs: [{ name: '', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    constant: true,
    stateMutability: 'view',
  },
  {
    name: 'sustainabilityPool',
    type: 'function',
    inputs: [{ name: '', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    constant: true,
    stateMutability: 'view',
  },
  {
    name: 'sustainedAddressesBySustainer',
    type: 'function',
    inputs: [
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    constant: true,
    stateMutability: 'view',
  },
  {
    name: 'getSustainerCount',
    type: 'function',
    inputs: [{ name: 'owner', type: 'address', internalType: 'address' }],
    outputs: [{ name: 'count', type: 'uint256', internalType: 'uint256' }],
    constant: true,
    stateMutability: 'view',
  },
  {
    name: 'getSustainmentTrackerAmount',
    type: 'function',
    inputs: [
      { name: 'owner', type: 'address', internalType: 'address' },
      { name: 'by', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: 'amount', type: 'uint256', internalType: 'uint256' }],
    constant: true,
    stateMutability: 'view',
  },
  {
    name: 'getRedistributionTrackerAmount',
    type: 'function',
    inputs: [
      { name: 'owner', type: 'address', internalType: 'address' },
      { name: 'by', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: 'amount', type: 'uint256', internalType: 'uint256' }],
    constant: true,
    stateMutability: 'view',
  },
  {
    name: 'sustain',
    type: 'function',
    inputs: [
      { name: 'owner', type: 'address', internalType: 'address' },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: 'success', type: 'bool', internalType: 'bool' }],
    stateMutability: 'nonpayable',
  },
  {
    name: 'collectRedistributions',
    type: 'function',
    inputs: [{ name: 'amount', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: 'success', type: 'bool', internalType: 'bool' }],
    stateMutability: 'nonpayable',
  },
  {
    name: 'collectRedistributionsFromAddress',
    type: 'function',
    inputs: [
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
      { name: 'from', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: 'success', type: 'bool', internalType: 'bool' }],
    stateMutability: 'nonpayable',
  },
  {
    name: 'collectRedistributionsFromAddresses',
    type: 'function',
    inputs: [
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
      { name: 'from', type: 'address[]', internalType: 'address[]' },
    ],
    outputs: [{ name: 'success', type: 'bool', internalType: 'bool' }],
    stateMutability: 'nonpayable',
  },
  {
    name: 'collectSustainments',
    type: 'function',
    inputs: [{ name: 'amount', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: 'success', type: 'bool', internalType: 'bool' }],
    stateMutability: 'nonpayable',
  },
  {
    name: 'configureMoneyPool',
    type: 'function',
    inputs: [
      { name: 'target', type: 'uint256', internalType: 'uint256' },
      { name: 'duration', type: 'uint256', internalType: 'uint256' },
      { name: 'want', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: 'success', type: 'bool', internalType: 'bool' }],
    stateMutability: 'nonpayable',
  },
]
